In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
print(np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
